### ISSUE TITLE
Build images for more recent versions of kubectl?

### ISSUE THREAD

**Issue by tomasaschan** [BuoyantIO/kubectl#1]
Thanks for an awesome toolset!

But this particular bit of it is a little outdated. I _could_ just clone your Dockerfile and create an image with a recent `kubectl` on it myself, but that wouldn't benefit anyone else.

Any chance of publishing versions of this image with more recent `kubectl` versions? Anything I can do to help?

**Comment by siggy** [comment]
@tomasaschan Thanks for the heads up, updated Dockerfile at #2, new images at https://hub.docker.com/r/buoyantio/kubectl/tags/.
