### ISSUE TITLE
Broken Dockerhub tag structure

### ISSUE THREAD

**Issue by rhyas** [BuoyantIO/kubectl#3]
The tag structure on the public dockerhub repo seems completely hosed. Many recent versions have recently gone missing are missing and latest links to a version published over a year ago.

**Comment by siggy** [comment]
@rhyas I've updated the `latest` tag to match `v1.12.2`. That was an oversight on my part when I pushed `v1.12.2` a few weeks ago.

Sounds like we have two separate issues:
1) no automation guaranteeing `latest` matches the actual latest build
2) no automation guaranteeing a docker image is pushed for every release of kubectl

If you're interested in addressing these, pull requests welcome.
